version: "2"
services:
  mongodb:
    container_name: usermanager_mongodb
    build: ./docker/db
    ports:
      - "27017:27017"
    networks:
      - main_network

networks: 
  main_network:
    driver: bridge