version: "2"
services:
  web:
    container_name: usermanager_web_app
    build: ./docker/app
    ports:
      - "3000:3000"
    networks:
      - main_network

  mongodb:
    container_name: usermanager_mongodb
    build: ./docker/db
    ports:
      - "27017:27017"
    networks:
      - main_network

networks: 
  main_network:
    driver: bridge